import { FormEvent, useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2, LogOut, MapPin, Package, Plus, Ticket } from 'lucide-react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { routes } from '../app/routes'
import { ShellSearch } from '../components/search/ShellSearch'
import { SiteShell } from '../components/layout/SiteShell'
import { Button } from '../components/ui/Button'
import { StatePanel } from '../components/ui/StatePanel'
import { TextInput } from '../components/ui/TextInput'
import { accountApi } from '../features/account/api/account.api'
import { authApi } from '../features/auth/api/auth.api'
import { useSiteChrome } from '../features/platform/hooks/useSiteChrome'
import { sessionStore } from '../shared/api/storage'

function Guard({ children }: { children: ReactNode }) { return sessionStore.hasSession() ? <>{children}</> : <Navigate to={routes.login} replace state={{ returnTo: routes.account }} /> }
function Frame({ children, notice, setNotice }: { children: ReactNode; notice?: string; setNotice: (value?: string) => void }) { const { navigation, currency, cartCount } = useSiteChrome(); return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} notice={notice} onDismissNotice={() => setNotice(undefined)} onAccountAction={() => undefined} onCartAction={() => undefined}>{children}</SiteShell> }
const links = [{ to: routes.account, label: 'حساب کاربری', Icon: Building2 }, { to: routes.addresses, label: 'نشانی‌ها', Icon: MapPin }, { to: routes.orders, label: 'سفارش‌ها', Icon: Package }, { to: routes.support, label: 'پشتیبانی', Icon: Ticket }]
export function AccountPage() { const navigate = useNavigate(); const [notice, setNotice] = useState<string>(); const me = useQuery({ queryKey: ['account', 'me'], queryFn: accountApi.me }); const logout = useMutation({ mutationFn: authApi.logout, onSuccess: () => navigate(routes.home) }); return <Guard><Frame notice={notice} setNotice={setNotice}><section className="account-page section container"><span className="section-kicker">حساب من</span><h1>{me.data?.name || 'حساب کاربری'}</h1><p className="page-lead">{me.data?.phone}</p><div className="account-links">{links.map(({ to, label, Icon }) => <Link key={to} to={to}><Icon /><span>{label}</span></Link>)}<Link to={routes.businessProfile}><Building2 /><span>پروفایل سازمانی</span></Link><button type="button" onClick={() => logout.mutate()}><LogOut /><span>خروج از حساب</span></button></div>{me.isError && <StatePanel kind="error" title="اطلاعات حساب دریافت نشد" />}</section></Frame></Guard> }
export function AddressesPage() { const [notice, setNotice] = useState<string>(); const client = useQueryClient(); const addresses = useQuery({ queryKey: ['account', 'addresses'], queryFn: accountApi.addresses }); const remove = useMutation({ mutationFn: (id: string) => { const address = addresses.data!.find((item) => item.id === id)!; return accountApi.removeAddress(id, address.version) }, onSuccess: () => client.invalidateQueries({ queryKey: ['account', 'addresses'] }), onError: () => setNotice('حذف نشانی انجام نشد.') }); return <Guard><Frame notice={notice} setNotice={setNotice}><section className="account-page section container"><span className="section-kicker">نشانی‌ها</span><h1>نشانی‌های ذخیره‌شده</h1>{addresses.isLoading && <StatePanel kind="loading" title="در حال دریافت نشانی‌ها" />}{addresses.data?.map((item) => <article className="account-row" key={item.id}><div><strong>{item.recipientName} {item.isDefault && <em>پیش‌فرض</em>}</strong><p>{item.addressLine}، {item.cityId}</p></div><Button variant="ghost" onClick={() => remove.mutate(item.id)}>حذف</Button></article>)}<Button onClick={() => window.location.assign(routes.checkoutAddress)}><Plus /> افزودن نشانی</Button></section></Frame></Guard> }
export function BusinessProfilePage() { const [notice, setNotice] = useState<string>(); const profile = useQuery({ queryKey: ['account', 'business'], queryFn: accountApi.businessProfile }); const save = useMutation({ mutationFn: (data: Record<string, string>) => accountApi.saveBusinessProfile({ ...data, version: profile.data?.version }), onSuccess: () => setNotice('پروفایل سازمانی ذخیره شد.'), onError: () => setNotice('ذخیره انجام نشد.') }); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); save.mutate({ organizationName: String(form.get('organizationName') || ''), nationalId: String(form.get('nationalId') || ''), economicCode: String(form.get('economicCode') || ''), landline: String(form.get('landline') || ''), invoiceNotes: String(form.get('invoiceNotes') || '') }) }; return <Guard><Frame notice={notice} setNotice={setNotice}><section className="account-page section container"><span className="section-kicker">پروفایل سازمانی</span><h1>اطلاعات فاکتور سازمانی</h1><form className="profile-form" onSubmit={submit}><TextInput name="organizationName" label="نام مجموعه" defaultValue={String(profile.data?.organizationName || '')} /><TextInput name="nationalId" label="شناسه ملی" defaultValue={String(profile.data?.nationalId || '')} /><TextInput name="economicCode" label="کد اقتصادی" defaultValue={String(profile.data?.economicCode || '')} /><TextInput name="landline" label="شماره ثابت" defaultValue={String(profile.data?.landline || '')} /><TextInput name="invoiceNotes" label="توضیحات فاکتور" defaultValue={String(profile.data?.invoiceNotes || '')} /><Button type="submit" disabled={save.isPending}>ذخیره</Button></form></section></Frame></Guard> }
