import { useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Navigate, useParams } from 'react-router-dom'
import { routeTo, routes } from '../app/routes'
import { ShellSearch } from '../components/search/ShellSearch'
import { SiteShell } from '../components/layout/SiteShell'
import { Button } from '../components/ui/Button'
import { StatePanel } from '../components/ui/StatePanel'
import { ordersApi } from '../features/orders/api/orders.api'
import { useSiteChrome } from '../features/platform/hooks/useSiteChrome'
import { sessionStore } from '../shared/api/storage'
const money = (value: number | string) => new Intl.NumberFormat('fa-IR').format(Number(value))
function Frame({ children }: { children: ReactNode }) { const { navigation, currency, cartCount } = useSiteChrome(); return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} onDismissNotice={() => undefined} onAccountAction={() => undefined} onCartAction={() => undefined}>{children}</SiteShell> }
export function OrdersPage() { const orders = useQuery({ queryKey: ['orders'], queryFn: ordersApi.list }); if (!sessionStore.hasSession()) return <Navigate to={routes.login} replace />; return <Frame><section className="account-page section container"><span className="section-kicker">سفارش‌ها</span><h1>سفارش‌های من</h1>{orders.isLoading && <StatePanel kind="loading" title="در حال دریافت سفارش‌ها" />}{orders.data?.length === 0 && <StatePanel kind="empty" title="هنوز سفارشی ندارید" />}{orders.data?.map((order) => <Link className="account-row account-row--link" key={order.id} to={routeTo.order(order.id)}><div><strong>{order.orderNumber}</strong><p>{new Date(order.createdAt).toLocaleDateString('fa-IR')} • {order.status}</p></div><b>{money(order.payable)} تومان</b></Link>)}</section></Frame> }
export function OrderDetailPage() { const { orderId = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState<string>(); const { navigation, currency, cartCount } = useSiteChrome(); const detail = useQuery({ queryKey: ['orders', orderId], queryFn: () => ordersApi.detail(orderId) }); const timeline = useQuery({ queryKey: ['orders', orderId, 'timeline'], queryFn: () => ordersApi.timeline(orderId) }); const shipments = useQuery({ queryKey: ['orders', orderId, 'shipments'], queryFn: () => ordersApi.shipments(orderId) }); const cancel = useMutation({ mutationFn: () => ordersApi.cancel(orderId, 'cancelled by customer'), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['orders', orderId] }); setNotice('درخواست لغو ثبت شد.') }, onError: () => setNotice('لغو سفارش ممکن نیست.') }); if (!sessionStore.hasSession()) return <Navigate to={routes.login} replace />; return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} notice={notice} onDismissNotice={() => setNotice(undefined)} onAccountAction={() => undefined} onCartAction={() => undefined}><section className="account-page section container">{detail.isLoading && <StatePanel kind="loading" title="در حال دریافت سفارش" />}{detail.data && <><span className="section-kicker">{detail.data.status}</span><h1>{detail.data.orderNumber}</h1><div className="order-detail-grid"><div><h2>اقلام سفارش</h2>{detail.data.lines.map((line) => <p className="account-row" key={line.id}><span>{line.product.title} × {line.quantity}</span><b>{money(line.lineSubtotal || 0)} تومان</b></p>)}<h2>روند سفارش</h2>{timeline.data?.map((item) => <p key={`${item.createdAt}-${item.newStatus}`}>{item.newStatus} <small>{new Date(item.createdAt).toLocaleString('fa-IR')}</small></p>)}</div><aside className="cart-summary"><h2>مبلغ پرداختی</h2><b>{money(detail.data.summary.payable)} تومان</b><p>وضعیت پرداخت: {detail.data.paymentStatus}</p>{shipments.data?.map((item) => <p key={item.id}>ارسال: {item.provider || '—'} {item.trackingCode || ''}</p>)}{detail.data.status === 'awaiting_payment' && <Button onClick={() => cancel.mutate()}>لغو سفارش</Button>}</aside></div></>}</section></SiteShell> }
