import { useState, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, BookOpen, CircleHelp, Mail, Phone } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { routeTo, routes } from '../app/routes'
import { ShellSearch } from '../components/search/ShellSearch'
import { SiteShell } from '../components/layout/SiteShell'
import { ProductCard } from '../components/ProductCard'
import { ButtonLink } from '../components/ui/Button'
import { StatePanel } from '../components/ui/StatePanel'
import { cartApi } from '../features/cart/api/cart.api'
import { catalogApi } from '../features/catalog/api/catalog.api'
import { useSiteChrome } from '../features/platform/hooks/useSiteChrome'
import type { ProductSummary } from '../types/catalog'

function PublicFrame({ children }: { children: ReactNode }) { const { navigation, currency, cartCount } = useSiteChrome(); return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} onDismissNotice={() => undefined} onAccountAction={() => undefined} onCartAction={() => undefined}>{children}</SiteShell> }
export function SeriesDetailPage() { const { seriesSlug = '' } = useParams(); const client = useQueryClient(); const [notice, setNotice] = useState<string>(); const series = useQuery({ queryKey: ['catalog', 'series', seriesSlug], queryFn: () => catalogApi.seriesDetail(seriesSlug, { pageSize: 24 }) }); const add = useMutation({ mutationFn: (item: ProductSummary) => cartApi.addItem(item.defaultSku!.id, item.defaultSku!.minimumQuantity), onSuccess: () => client.invalidateQueries({ queryKey: ['cart', 'current'] }), onError: () => setNotice('افزودن به سبد انجام نشد.') }); const { navigation, currency, cartCount } = useSiteChrome(); return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} notice={notice} onDismissNotice={() => setNotice(undefined)} onAccountAction={() => undefined} onCartAction={() => undefined}><section className="series-page section container">{series.isLoading && <StatePanel kind="loading" title="در حال دریافت مجموعه" />}{series.isError && <StatePanel kind="error" title="مجموعه پیدا نشد" actionLabel="بازگشت به مجموعه‌ها" onAction={() => window.location.assign(routes.seriesIndex)} />}{series.data && <><span className="section-kicker">مجموعه کتاب</span><h1>{series.data.series.name}</h1><p className="page-lead">{new Intl.NumberFormat('fa-IR').format(series.data.products.total)} عنوان قابل سفارش در این مجموعه</p><div className="products-grid catalog-products">{series.data.products.items.map((item) => <ProductCard key={item.id} product={item} href={routeTo.product(item.slug)} onAdd={async (product) => { await add.mutateAsync(product) }} adding={add.isPending && add.variables?.id === item.id} />)}</div></>}</section></SiteShell> }
export function HelpPage() { return <PublicFrame><section className="help-page section container"><span className="section-kicker">راهنمای مشتریان</span><h1>چطور می‌توانیم کمک کنیم؟</h1><div className="help-grid"><article><BookOpen /><h2>ثبت سفارش</h2><p>کتاب‌ها را به سبد اضافه کنید، نشانی و روش ارسال را انتخاب و پرداخت را تکمیل کنید.</p><Link to={routes.wholesaleGuide}>راهنمای خرید عمده <ArrowLeft /></Link></article><article><CircleHelp /><h2>پیگیری سفارش</h2><p>وضعیت سفارش و مرسوله از بخش حساب کاربری قابل مشاهده است.</p><Link to={routes.orders}>مشاهده سفارش‌ها <ArrowLeft /></Link></article><article><Phone /><h2>تماس با فروش</h2><p>شنبه تا پنجشنبه، ۹ تا ۱۸ پاسخ‌گوی سفارش‌های سازمانی هستیم.</p><a href="tel:02166974420">۰۲۱-۶۶۹۷۴۴۲۰</a></article></div><div className="help-faq"><h2>پرسش‌های پرتکرار</h2><details><summary>حداقل تعداد سفارش هر کتاب چقدر است؟</summary><p>حداقل سفارش در صفحهٔ همان کتاب و پیش از افزودن به سبد نشان داده می‌شود.</p></details><details><summary>چگونه برای سفارش عمده تخفیف می‌گیرم؟</summary><p>قیمت‌گذاری پلکانی به‌صورت خودکار و براساس تعداد هر عنوان در سبد محاسبه می‌شود.</p></details><details><summary>برای پشتیبانی پس از خرید چه کنم؟</summary><p>پس از ورود، از بخش پشتیبانی حساب کاربری تیکت ثبت کنید.</p></details></div><ButtonLink href="mailto:sales@pardisbook.ir"><Mail /> ارسال ایمیل به فروش</ButtonLink></section></PublicFrame> }
export function NotFoundPage() { return <PublicFrame><section className="not-found section container"><span>۴۰۴</span><h1>این صفحه پیدا نشد</h1><p>ممکن است نشانی تغییر کرده باشد یا دیگر در دسترس نباشد.</p><ButtonLink href={routes.home}>بازگشت به خانه</ButtonLink></section></PublicFrame> }
