import { FormEvent, type ReactNode } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { routeTo, routes } from '../app/routes'
import { ShellSearch } from '../components/search/ShellSearch'
import { SiteShell } from '../components/layout/SiteShell'
import { Button } from '../components/ui/Button'
import { StatePanel } from '../components/ui/StatePanel'
import { TextInput } from '../components/ui/TextInput'
import { useSiteChrome } from '../features/platform/hooks/useSiteChrome'
import { supportApi } from '../features/support/api/support.api'
import { sessionStore } from '../shared/api/storage'
function Frame({ children }: { children: ReactNode }) { const { navigation, currency, cartCount } = useSiteChrome(); return <SiteShell navigation={navigation} phone="۰۲۱-۶۶۹۷۴۴۲۰" currency={currency} cartCount={cartCount} headerSearch={<ShellSearch />} onDismissNotice={() => undefined} onAccountAction={() => undefined} onCartAction={() => undefined}>{children}</SiteShell> }
export function SupportPage() { const navigate = useNavigate(); const tickets = useQuery({ queryKey: ['support', 'tickets'], queryFn: supportApi.tickets }); const categories = useQuery({ queryKey: ['support', 'categories'], queryFn: supportApi.categories }); const create = useMutation({ mutationFn: (data: { categoryId: string; title: string; description: string }) => supportApi.createTicket(data), onSuccess: (ticket) => navigate(routeTo.supportTicket(ticket.id)) }); if (!sessionStore.hasSession()) return <Navigate to={routes.login} replace />; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ categoryId: String(data.get('categoryId')), title: String(data.get('title')), description: String(data.get('description')) }) }; return <Frame><section className="account-page section container"><span className="section-kicker">پشتیبانی</span><h1>تیکت‌های من</h1><form className="support-form" onSubmit={submit}><select required name="categoryId" defaultValue=""><option value="" disabled>دسته‌بندی را انتخاب کنید</option>{categories.data?.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><TextInput required name="title" label="موضوع" /><label className="field"><span className="field__label">شرح درخواست</span><textarea className="field__control" required name="description" rows={4} /></label><Button type="submit" disabled={create.isPending}>ثبت تیکت</Button></form>{tickets.isLoading && <StatePanel kind="loading" title="در حال دریافت تیکت‌ها" />}{tickets.data?.map((ticket) => <Link className="account-row account-row--link" key={ticket.id} to={routeTo.supportTicket(ticket.id)}><div><strong>{ticket.title}</strong><p>{ticket.status}</p></div><small>{new Date(ticket.updatedAt).toLocaleDateString('fa-IR')}</small></Link>)}</section></Frame> }
export function SupportTicketPage() { const { ticketId = '' } = useParams(); const client = useQueryClient(); const ticket = useQuery({ queryKey: ['support', ticketId], queryFn: () => supportApi.ticket(ticketId) }); const add = useMutation({ mutationFn: (body: string) => supportApi.addMessage(ticketId, body), onSuccess: () => client.invalidateQueries({ queryKey: ['support', ticketId] }) }); if (!sessionStore.hasSession()) return <Navigate to={routes.login} replace />; return <Frame><section className="account-page section container">{ticket.isLoading && <StatePanel kind="loading" title="در حال دریافت تیکت" />}{ticket.data && <><span className="section-kicker">{ticket.data.status}</span><h1>{ticket.data.title}</h1><div className="ticket-thread">{ticket.data.messages.map((message) => <p className={message.isStaff ? 'is-staff' : ''} key={message.id}>{message.body}<small>{new Date(message.createdAt).toLocaleString('fa-IR')}</small></p>)}</div><form onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const body = String(new FormData(event.currentTarget).get('body') || ''); if (body) { add.mutate(body); event.currentTarget.reset() } }} className="ticket-reply"><textarea name="body" required placeholder="پیام شما…" /><Button type="submit" disabled={add.isPending}>ارسال پیام</Button></form></>}</section></Frame> }
