export const routes = {
  home: '/',
  catalog: '/books',
  search: '/search',
  seriesIndex: '/series',
  series: '/series/:seriesSlug',
  product: '/books/:productSlug',
  wholesaleGuide: '/wholesale-guide',
  login: '/login',
  otp: '/login/otp',
  buyerProfile: '/onboarding',
  cart: '/cart',
  checkoutAddress: '/checkout/address',
  checkoutShipping: '/checkout/shipping',
  checkoutReview: '/checkout/review',
  paymentResult: '/payment/result',
  account: '/account',
  addresses: '/account/addresses',
  businessProfile: '/account/business',
  orders: '/account/orders',
  orderDetail: '/account/orders/:orderId',
  help: '/help',
  support: '/account/support',
  supportTicket: '/account/support/:ticketId',
} as const

export const routeTo = {
  series: (seriesSlug: string) => `/series/${encodeURIComponent(seriesSlug)}`,
  product: (productSlug: string) => `/books/${encodeURIComponent(productSlug)}`,
  order: (orderId: string) => `/account/orders/${encodeURIComponent(orderId)}`,
  supportTicket: (ticketId: string) => `/account/support/${encodeURIComponent(ticketId)}`,
  search: (query: string) => `/search?q=${encodeURIComponent(query)}`,
  catalogSearch: (query: string) => `/books?q=${encodeURIComponent(query)}`,
}

export const routeManifest = [
  { path: routes.home, access: 'public', phase: 2 },
  { path: routes.catalog, access: 'public', phase: 3 },
  { path: routes.search, access: 'public', phase: 2 },
  { path: routes.seriesIndex, access: 'public', phase: 2 },
  { path: routes.series, access: 'public', phase: 3 },
  { path: routes.product, access: 'public', phase: 3 },
  { path: routes.wholesaleGuide, access: 'public', phase: 2 },
  { path: routes.login, access: 'guest', phase: 4 },
  { path: routes.otp, access: 'guest', phase: 4 },
  { path: routes.buyerProfile, access: 'authenticated', phase: 4 },
  { path: routes.cart, access: 'public', phase: 4 },
  { path: routes.checkoutAddress, access: 'authenticated', phase: 5 },
  { path: routes.checkoutShipping, access: 'authenticated', phase: 5 },
  { path: routes.checkoutReview, access: 'authenticated', phase: 5 },
  { path: routes.paymentResult, access: 'authenticated', phase: 5 },
  { path: routes.account, access: 'authenticated', phase: 6 },
  { path: routes.addresses, access: 'authenticated', phase: 5 },
  { path: routes.businessProfile, access: 'authenticated', phase: 6 },
  { path: routes.orders, access: 'authenticated', phase: 6 },
  { path: routes.orderDetail, access: 'authenticated', phase: 6 },
  { path: routes.help, access: 'public', phase: 6 },
  { path: routes.support, access: 'authenticated', phase: 6 },
  { path: routes.supportTicket, access: 'authenticated', phase: 6 },
] as const
